apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
spec:
  template:
    spec:
      containers:
        - image: 953533/coit-frontend:v20
          imagePullPolicy: Always                         # 7
          name: coit-frontend
          ports:
            - containerPort: 8080
