apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coit-backend1-mystaticfiles
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-good-for-dbs

