apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-fast
parameters:
  type: gp2
  fstype: ext4
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
